apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: ak-ambulance-wl # napr. <pfx>-ambulance-wl
spec:
  title: "Zoznam čakajúcich ak"
  description: "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii"
  authors: "Adrian Komanek" # Zadajte mená autorov
  azureLink: "https://<sub-domain>.azurewebsites.net"
  frontendRepoUrl: "https://github.com/K-o-m-A/ak-ambulance-ufe"
  backendRepoUrl: "https://github.com/K-o-m-A/ak-ambulance-webapi"
  gitopsRepoUrl: "https://github.com/K-o-m-A/ak-ambulance-gitops"