apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: hocikto/ambulance-ufe
  newName: hocikto/ambulance-ufe
  newTag: main.20260309.1105 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
